### PR TITLE
Add 'processEvent' to debug protocol

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This defines a new 'processEvent' to resolve https://github.com/Microsoft/vscode-debugadapter-node/issues/122

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
FYI @andrewcrawley @DavidKarlas @weinand

**Comment by andrewcrawley** [comment]
LGTM.  When would `isLocalProcess` be false?  Every "remote" scenario I'm aware of has the machine boundary between the UI and the debug adapter, not between the DA and the debuggee.

**Comment by gregg-miskelly** [comment]
@andrewcrawley -- the one case that I know of today where we would set this would be in vsdbg-ui for VS Code and VS For Mac. I wouldn't expect vsdbg to set this at all, since it never knows if it is remote debugging or note.

**Comment by DavidKarlas** [comment]
LGTM

**Comment by weinand** [comment]
FYI: Debug adapters cannot run remote because the DAP uses local file paths, so there is an assumption that they run side by side with the frontend/client and they have access to the workspace.
It would be possible to remove this assumption (by changing the DAP), but this would be a breaking change.

**Comment by weinand** [comment]
@andrewcrawley Perfect! Thanks for the PR.

**Pull request merged**
