### PR TITLE
Allow requests to specify formatting hints.

### PR DESCRIPTION
**Pull request by richardstanton**
Add optional formatting object to allow customization on how values and stack frames are displayed.

@weinand
@jacdavis @gregg-miskelly @andrewcrawley  @tzwlai

### CODE REVIEW

**Comment by weinand** [comment]
@richardstanton before sending a PR please create an issue that explains the protocol additions and where we can discuss it.

**Comment by richardstanton** [comment]
@weinand I created an issue for this. Sorry, I misunderstood the process for protocol changes. https://github.com/Microsoft/vscode-debugadapter-node/issues/84

**Comment by weinand** [comment]
@richardstanton great, thanks a lot. In VS Code we always try to have a feature discussion before a PR is created. With this we try to avoid that a PR diverges too much from our own plans and thinking.

**Comment by weinand** [comment]
@richardstanton thanks for this PR!

**Pull request closed without merging**
